### ISSUE TITLE
Fix: 404 Page Routing Redirects to Goldydocs of Netlify Instead of Custom 404 Page

### ISSUE THREAD

**Issue by UrielOfir** [Maakaf/maakaf_home#1]
## Issue Description

When accessing non-existent routes on the website, users are incorrectly redirected to a Goldydocs page instead of our custom 404 error page.

### Expected Behavior
- Non-existent routes should display our custom Hebrew 404 error page
- The HTTP status code should be 404
- Users should see the message "הדף לא נמצא" with a link back to the homepage

### Current Behavior
- Non-existent routes redirect to a Goldydocs page
- The custom 404 page is not being served
- Users see unrelated content instead of the proper error message

### Root Cause
The issue stems from incorrect configuration in multiple places:
1. Missing dedicated 404 page in the Hebrew content directory
2. Incorrect Netlify redirect configuration
3. Incomplete Hugo output and page handling configuration

### 1. Created Hebrew 404 Page
Added a dedicated 404 page in the Hebrew content directory:
```markdown
---
title: "הדף לא נמצא"
layout: "404"
---

# הדף לא נמצא

אופס! הדף הזה לא קיים. נסה לחזור אל [דף הבית](/).
```

### 2. Updated Netlify Configuration
Modified `netlify.toml` to properly handle 404 redirects:
```toml
[[redirects]]
  from = "/*"
  to = "/he/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
```

### 3. Updated Hugo Configuration
Modified `hugo.yaml` to ensure proper 404 page handling:
```yaml
outputs:
  section: [HTML, RSS]
  home: [HTML, RSS]
  page: [HTML]
  404: [HTML]

disableAliases: true
```

## Testing
To verify the fix:
1. Run the site locally using `hugo server`
2. Try accessing a non-existent URL (e.g., `http://localhost:1313/non-existent-page`)
3. Verify that the Hebrew 404 page is displayed
4. Check that the HTTP status code is 404

## Additional Notes
- This fix ensures proper 404 handling while maintaining security headers
- The solution respects the site's multilingual setup with Hebrew as the default language
- The fix prevents unwanted redirects and maintains proper HTTP status codes

## Related Documentation
- [Hugo 404 Pages](https://gohugo.io/templates/404/)
- [Netlify Custom 404](https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling)
